Preferences.addAll([
	{ id: "extensions.roomybookmarkstoolbar.mousehover", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.hideBookmarksName", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.hideFoldersNames", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.hideNoFaviconNames", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.hideFolderIcons", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.hideBookmarksIcons", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.hideDefaultIcons", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.spacing", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.iconSize", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.location", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.userWidthEnabled", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.userWidth", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.autoHideBar", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.autoHideBarTime", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.autoHideZoneTab", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.autoHideZoneNav", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.autoHideZoneMenu", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.autoHideZoneButton", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.autoHideZoneBackButton", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.autoHideZoneMenuButton", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.autoHideZoneAll", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.hideByDefault", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.BBonNewTab", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.opacity", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.opacityTime", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.opacityTimeLong", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.multirowBar", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.rows", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.fixedHeight", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.heightFix", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.bookmarksAboveTab", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.overPage", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.folderMargin", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.height", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.DBcreated", type: "bool" },
	{ id: "extensions.roomybookmarkstoolbar.textSize", type: "int" },
	{ id: "extensions.roomybookmarkstoolbar.hide_warning", type: "bool" },
]);

	